engines:
  fixme:
    enabled: true
  pmd:
    enabled: true
    channel: "beta"
  checkstyle:
    enabled: true
    channel: "beta"
ratings:
  paths:
  - "**.java"
exclude_paths:
# - eg "tests/" here
