kind: pipeline
name: default

steps:
  - name: build
    image: openjdk:8-jdk-slim
    commands:
      - ./gradlew build -x test

  - name: test
    image: openjdk:8-jdk-slim
    commands:
      - ./gradlew test jacocoTestReport

  - name: coverage
    image: plugins/codecov
    settings:
      token:
        from_secret: codecov-token
      files:
        - "*.xml"
      paths:
        - build/reports/jacoco/test