language: java
jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "amdelamar-github"

before_install:
 - chmod +x gradlew

script:
 - ./gradlew check
 - ./gradlew jacocoTestReport
after_success:
 - bash <(curl -s https://codecov.io/bash)
